### ISSUE TITLE
Funnel TES v1.1 Compliance Tasks 

### ISSUE THREAD

**Issue by lbeckman314** [ohsu-comp-bio/funnel#679]
# Tasks

- [ ] Create task with correct JSON validation
- [ ] Create task with backend_parameters" in tesResources
- [ ] Create task with file type as an optional argument
- [ ] Create task with wildcards in output paths
- [ ] Create task with streamable flag in tesInput 
- [ ] Get basic view of a given task
- [ ] Get full view of a given task
- [ ] List basic view of tasks
- [ ] List full view of tasks
- [ ] Correct service info endpoint

---

## [tes-compliance-suite full report](https://ohsu-comp-bio.github.io/funnel-compliance/v1_1.html)

| Phase                                    | Test         | Case                         | Status |
| ---------------------------------------- | ------------ | ---------------------------- | ------ |
| phase_create_task.yml                    | create_task  | request_body_json_validation | FAIL   |
| phase_create_task_backend_parameters.yml | create_task  | status_code                  | FAIL   |
| phase_create_task_optional_filetype.yml  | create_task  | request_body_json_validation | FAIL   |
| phase_create_task_output.yml             | create_task  | request_body_json_validation | FAIL   |
| phase_create_task_streamable.yml         | create_task  | status_code                  | FAIL   |
| phase_get_task_basic.yml                 | get_task     | response_schema_validation   | FAIL   |
| phase_get_task_full.yml                  | get_task     | response_schema_validation   | FAIL   |
| phase_list_tasks_basic.yml               | list_tasks   | response_schema_validation   | FAIL   |
| phase_list_tasks_full.yml                | list_tasks   | response_schema_validation   | FAIL   |
| phase_service_info.yml                   | service_info | response_schema_validation   | FAIL   |

---

## References
- [TES v1.1 Release Page](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1)
- [ELIXR Cloud & AAI tes-compliance-suite](https://github.com/elixir-cloud-aai/tes-compliance-suite/pull/29)

**Comment by lbeckman314** [comment]
Closing in favor of separate issues #679 - #689 (see updated tasks view above).
